### ISSUE TITLE
conflict slua with UNetWeaver in Unity 5.2.x

### ISSUE THREAD

**Issue by Salada** [pangweiwei/slua#100]
I see this issue http://www.unityqa.com/?/article/5 and i was suffered same issue at post.

when i attempt to upgrade unity 5.2.2, if Assembly-CSharp.dll or Assembly-CSharp-fistpass.dll size is much big, this issue is occured. ( but information is lack and uncertain )

I think this issue is only caused by UNetWeaver. because this option is not possibly switched turn on-off in unity, in addition, UNetWeaver use too many reflection for making inner structure.

but our project need fast workaround solution, then choose below it.

* commit list in our project.

  * rename base folder structure -> https://github.com/thing-nacho/slua/commit/360fec6d27926734118e28c6b6982837c0458ed3

* then change generated code path ( Only UnityEngine codegen ) for reduce Assembly-CSharp.dll binary size.

  * https://github.com/thing-nacho/slua/blob/305d749b4ac5521fd051ec33ed87056317ddb193/Assets/Slua/Editor/LuaCodeGen.cs#L152

* Operating SLua in plugin folder make possible, change class accessor and treat misc problem
  * https://github.com/thing-nacho/slua/commit/542429d4ff758560c12f80445f3591011005bd12
  * https://github.com/thing-nacho/slua/commit/8c4ee600dc340f58fba0f7e8bcd244f6dc6afbaa
  * https://github.com/thing-nacho/slua/commit/2e517956542249573179c05623ec94cdf94517ff

i don't hope to accept my solution.
this issue only suggestion for sharing necessity that Assembly-CSharp.dll binary size must be reduced.

thanks.

**Comment by pangweiwei** [comment]
refer this issue https://github.com/pangweiwei/slua/issues/73

I found that you put slua/script folder to "Standard Assets" folder let unity generate "Assembly-CSharp-firstpass.dll", UNetWeaver will not report error.

**Comment by wlgys8** [comment]
I suffered the same issue yesterday

**Comment by pangweiwei** [comment]
I had pushed a fix based on @Salada method.

**Comment by Salada** [comment]
thanks hear my opinion. but i still think this problem's responsibility is to unity... 
i hope this solution is only temporary workaround for supporting Unity 5.2.x....

**Comment by Salada** [comment]
check this commit plz https://github.com/thing-nacho/slua/commit/2e517956542249573179c05623ec94cdf94517ff

if target folder for slua script and generated code move to "Standard Assets" or "Plugins", Type.GetType() is failed.

**Comment by wlgys8** [comment]
https://github.com/jbevain/cecil/issues/241

opinion from ceil author

**Comment by pangweiwei** [comment]
Not only temp workaround for Unity 5.2.x, but also put slua scripts to Plugins is better structure. So I restructure them.

Now you can delete slua folder from Assets, it's only for example or your custom wrap.
