### ISSUE TITLE
UnityEngine导出文件放到Plugins后会引起扩展方法找不到的问题

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#103]
例如对Sprite定义了一些扩展方法放到文件 SpriteExt.cs 中。

这个SpriteExt.cs是在`Assembly-CSharp`中的,而Lua_UnityEngine_Sprite是在`Assembly-CSharp-firstpass`中，引用不到SpriteExt.cs

**Comment by pangweiwei** [comment]
嗯，该了目录结构，这到是个问题了:(

**Comment by pangweiwei** [comment]
我刚才看到5.2.3发布了，貌似修复UNetWeaver的bug

**Comment by pangweiwei** [comment]
你可以考虑revert之前的目录结构，就不存在这个问题了

**Comment by wlgys8** [comment]
我把generate code path改回到了之前的目录。
其他的还是遵循现在新的目录结构吧。

5.2.3  的release note里好像没看到关于UNetWeaver那个问题的说明？
只看到了`(none) - Networking: Fix for UNetWeaver exception when making Metro builds`这个，针对metro的

**Comment by pangweiwei** [comment]
Networking: Fixed code generation execption when using certain build-in unity types ...

这个估计是个fix，猜的

**Comment by wlgys8** [comment]
还有一个问题:
Plugins/SLua_Managed/Editor 这个目录下的文件似乎会被编译到`Assembly-CSharp-firstpass`中 而不是`Assembly-CSharp-Editor-firstpass`,
build的时候会报错,引用了UnityEditor

**Comment by Salada** [comment]
@wlgys8 I think this document is good reference
http://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html

Phase 1 is compiled to Assembly-CSharp-firstpass.dll
Phase 2 is compiled to Assembly-CSharp-Editor-firstpass.dll ( depends Assembly-CSharp-firstpass.dll )
Phase 3 is compiled to Assembly-CSharp.dll ( depends Assembly-CSharp-firstpass.dll )
Phase 4 is compiled to Assembly-CSharp-Editor.dll ( depends above all )

**Comment by wlgys8** [comment]
@Salada 
I'v read this document. The issue is:
If we define some extension methods for `UnityEngine.Sprite` in `SpriteExt.cs`,
1.`SpriteExt.cs` will be compiled into `Assembly-CSharp.dll`
2.`Lua_UnityEngine_Sprite.cs will be compiled into `Assembly-CSharp-firstpass.dll`

We can not access SpriteExt.cs  in Lua_UnityEngine_Sprite.cs.
This will cause a compile error.

**Comment by Salada** [comment]
If want to use method extensions by class in UnityEngine.dll, I think need to 2 bind load phase and codegen phase. but changelist expect too many. and i have just idea. not attempt to implement this feature.

I turn off about extensions method, can't catch this problem :(

I think Editor folder need to be located in /Editor not in /Plugins/Editor, Assembly-CSharp-Editor-firstpass.dll not access Assembly-CSharp.dll. then your needs is accomplished.

**Comment by wlgys8** [comment]
@Salada 
I agree with you

**Comment by wlgys8** [comment]
If put Editor folder under Plugins and do make UnityEngine, this exception will be thrown:

		System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp-Editor' or one of its dependencies. The system cannot find the file specified.
		File name: 'Assembly-CSharp-Editor'

The reason is  ` Assembly-CSharp-Editor.dll` is compiled later than `Assembly-CSharp-Editor-firstpass.dll`.

So, we should move Editor folder back to Assets/Slua/Editor?

**Comment by wlgys8** [comment]
If put folder `Editor` under `Plugins`
LuaCodeGen.InvokeEditorMethod will throw error below:
		System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp-Editor' or one of its dependencies. The system cannot find the file specified.
		File name: 'Assembly-CSharp-Editor'
Should move folder `editor` back to Assets/Slua/Editor ?

**Comment by pangweiwei** [comment]
ok
