### ISSUE TITLE
strict.lua check failed when debugging with DebugInterface。

### ISSUE THREAD

**Issue by c3076802** [pangweiwei/slua#108]
We are using strict.lua to check if any global is used without declaration.

SLuaDebug.cs line 107 fails the check.
```lua
local function buildEnv()
		local localEnv = setmetatable({}, {__index=_G})
		local setVariable = _G  --local keyword should be added
...
```
BTW How about debugging lua with zeroBrane ？

**Comment by pangweiwei** [comment]
Thanks report bug at first.

Slua remote debugger used to debug APP in mobile device via TCP/IP connection on fly( also support local computer) , zeroBrane or other IDE debug code in local computer via hook Lua API on startup, I suggest you use slua debugger strongly, if you prefer IDE, you can read their documents.

**Comment by c3076802** [comment]
Thank you for your response, that was quick!
