### ISSUE TITLE
Lua3rdDLL.open(L) takes about 1.3 sec but doing nothing

### ISSUE THREAD

**Issue by c3076802** [pangweiwei/slua#110]
I notice in file LuaSvr.cs function doinit(),  calls to Lua3rdDLL.open(L) take about 1.3 sec but doing nothing and GC alloc goes up to 37mb
Seems the code as follows cause the problem.
```C#
var csfunctions = assembly.GetExportedTypes()
					.SelectMany(x => x.GetMethods())
						.Where(y => y.GetCustomAttributes(typeof(LualibRegAttribute),false).Any())
						.ToList();
```
Any Idea ? Thanks !

**Comment by c3076802** [comment]
I remove Lua3rdDLL.open(L) from doinit(), It works just fine.

**Comment by pangweiwei** [comment]
These codes contributed by @wlgys8

**Comment by pangweiwei** [comment]
I have profiled, but didn't get similar output, I found gc alloc need 6MB and take 150ms on pc.

I have reviewed the code and modified a little for reduce gc alloc, after my modification, gc alloc need 345kb and take 26ms.

**Comment by c3076802** [comment]
I just retested result as follows
without profiler
```
find all methods marked by [Lua3rdRegAttribute] cost :0.5860335
```

profiler result
![profiler](https://cloud.githubusercontent.com/assets/3726167/11520857/1e2ca06c-98e2-11e5-8caa-e50e1c51523c.png)

then I remove Lua3rdDLL.open(L)
![p2](https://cloud.githubusercontent.com/assets/3726167/11520966/f4821886-98e2-11e5-9c93-12ff6e2e4396.PNG)

The problem of Lua3rdDLL.open(L) is the function actually doing nothing (to me because I don't have any 3rdDll to be imported). It should be able to disable and enable when needed.  
BTW I am pretty new to Unity my conclusion might not very accurate, Thank.

**Comment by pangweiwei** [comment]
I added a flag to control whether switch on debug/open extlib/reg 3rddll or not, not need reg 3rddll as default for most user.

**Comment by pangweiwei** [comment]
![prof](https://cloud.githubusercontent.com/assets/6227270/11521115/52e9c116-98e4-11e5-89c5-a2335d6280d4.png)

Notice my capture, xxx only need 0.7M gc-alloc and take 56ms on pc(latest version), I think you should expand profile tree to scrutinize what's hot spot.

**Comment by c3076802** [comment]
Thanks !
![image](https://cloud.githubusercontent.com/assets/3726167/11521285/cd664fbc-98e5-11e5-899c-256ad147c565.png)
Expanding profile tree on  just halted my shitty machine...
```C#
Profiler.BeginSample("xxxx");
Lua3rdDLL.open(L);
Profiler.EndSample();
```
I will give this a try.

**Comment by c3076802** [comment]
New test



With your latest Fix

![p5](https://cloud.githubusercontent.com/assets/3726167/11521956/fde36e5c-98ec-11e5-8b00-eb606c7376ba.PNG)

**Comment by pangweiwei** [comment]
Did you did some 3rd dll reg work?

**Comment by pangweiwei** [comment]
I get it, your assembly contains much functions, I had added a binding flat to reduce list of function that are returned by x.GetMethods

**Comment by c3076802** [comment]
Yes I bought quite a few plugins with dlls such as Json.Net for Unity.

**Comment by c3076802** [comment]
```C#
			foreach(var assem in AppDomain.CurrentDomain.GetAssemblies()){
				if(assem.GetName().Name == "Assembly-CSharp"){
					assembly = assem;
				}
			}
```
break is needed when assembly is found I guess.

**Comment by pangweiwei** [comment]
I think so ,had fixed

**Comment by wlgys8** [comment]
maybe auto search is not a good solution here? 
ease use but time costing.
register 3rd DLL manually seems better?
