### ISSUE TITLE
Suggestions of DebugInterface

### ISSUE THREAD

**Issue by c3076802** [pangweiwei/slua#111]
1. Can DebugInterface's debug addr and port be configurated？
2. Can DebugInterface be disable and enable at runtime?

A few words about the suggestions, We would like to have DebugInterface be complied with our releasing game (as the last solution to save our ass), but we don't want it be enabled every time, it would be enabled when needed only. 
We have developed some games with cocos, we have developed a similar debugger like DebugInterface, here is how we handles:

1. Read debug addr and debug port from a config at persistentDataPath
2. If debug addr and port exist then starts the debugger.

**Comment by pangweiwei** [comment]
Can DebugInterface be disable and enable at runtime?
Had add a flag to control it on startup.

**Comment by c3076802** [comment]
I already did it, I hope this idea will get in to the trunk somehow, then I don't to merge when next update 
:-p. 
Thanks

**Comment by pangweiwei** [comment]
Had read debug ip/port from sluasetting
