### ISSUE TITLE
Unity打包版本Mono内存泄漏问题（无论是windows版本还是设备版本）

### ISSUE THREAD

**Issue by tony-tang** [pangweiwei/slua#122]
现象：在Editor中运行正常，ObjectCache中的垃圾都会被回收掉，但是打包后运行版本ObjectCache中的已经被Destroy的UnityEngine.Object不会被垃圾回收，导致Mono用到的内存会越来越高。
截图1：
![image](https://cloud.githubusercontent.com/assets/1984494/12370717/86675284-bc56-11e5-94e8-13611d5d7d1e.png)
多次点击GC后，截图2：
![image](https://cloud.githubusercontent.com/assets/1984494/12370722/af15bf36-bc56-11e5-903b-74d532f8d71e.png)
可以看到，正常的object已经被gc，但是为null的UnityObject未被释放。

原因：Unity Editor中跟正常运行的打包版本，UnityEngine.Object处理不同，在UnityEditor中，当一个UnityObject被释放后，调用 GetHashCode()方法还是可以取到正确的值（释放的不是很彻底），但是打包版本调用此方法时，返回的是0

解决方法：ObjectCache修改objMap的Dictionary比较器
```c#
        public class ObjEqualityComparer : IEqualityComparer<object>
        {
            public bool Equals(object x, object y)
            {

                return ReferenceEquals(x, y);
            }

            public int GetHashCode(object obj)
            {
                return RuntimeHelpers.GetHashCode(obj);
            }
        }

		Dictionary<object, int> objMap = new Dictionary<object, int>(new ObjEqualityComparer());
```
这个bug我们找了整整2天，测试代码无法上传，自己修改Dictionary<object, int> objMap为public，写个监控即可。

**Comment by pangweiwei** [comment]
你的测试版本是多少？

**Comment by tony-tang** [comment]
Slua最新版本，Unity 5.3.0

**Comment by pangweiwei** [comment]
我测试了一下，没有发现你说的问题，测试代码如下：
function main()
	for i=1,100 do
		local g=GameObject("ml"..tostring(i))
		GameObject.Destroy(g)
	end

	local go = GameObject.Find("Canvas/Button")
	local btn = go:GetComponent("Button")

	
	

	btn.onClick:AddListener(function()
		collectgarbage()
	end)
	

	
end

点击按钮后，所有gameobject都被回收了，并且objMap的count为0，表明都被gc掉了。

**Comment by pangweiwei** [comment]
该问题仅针对于Unity3D 5.3版本（可能包含其他5.x版本），但4.x系列不存在此问题。
