### ISSUE TITLE
从lua传递binary string到c#的问题

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#125]
c#向lua传递可以通过:
1.传递byte[] 到 lua
2.用Slua.ToString()转换

但是从lua传递到c#呢？ 
现在是不是没有这样的接口？
我直接传的话会挂在: Marshal.PtrToStringAnsi

        public static string lua_tostring(IntPtr luaState, int index)
        {
            int strlen;

            IntPtr str = luaS_tolstring32(luaState, index, out strlen); // fix il2cpp 64 bit

            if (str != IntPtr.Zero)
            {
				var ret =  Marshal.PtrToStringAnsi(str, strlen);
				return ret;
            }
            return null;
        }

**Comment by chiuan** [comment]
你新版本的话要自己实现checkArray里面处理你这个byte[]即可

**Comment by pangweiwei** [comment]
我remove了之前可以使用string来checkType<byte[]>，我建议实现自己的buffer类，导出到lua来传递byte[]。

**Comment by wlgys8** [comment]
get it

**Comment by wlgys8** [comment]
给Slua加了一个ToBytes的方法来解决这个问题，不知道是否合适.
https://github.com/pangweiwei/slua/pull/128
