### ISSUE TITLE
Slua do not support bitcode for ios.

### ISSUE THREAD

**Issue by heha** [pangweiwei/slua#126]
Since Unity 5.3 release, bitcode is now fully supported. (https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)

However, when I tried to build slua in ios, it stated that this lib do not support bitcode yet. Do you have a plan to support it?

**Comment by pangweiwei** [comment]
What's it used for?

**Comment by heha** [comment]
In short, this let apple to cut down size on binary of Universal app (which included all arm7, arm64 architecture in download even though, that device need only 1 architecture support.) and send only architecture the device requested for download so, the final binary in the device could be a lot smaller. For a long version, please see below:

> What does the ENABLE_BITCODE actually do, will it be a non-optional requirement in the future?
> I'm not sure at what level you are looking for an answer at, so let's take a little trip. Some of this you may already know.
> 
> When you build your project, Xcode invokes clang for Objective-C targets and swift/swiftc for Swift targets. Both of these compilers compile the app to an intermediate representation (IR), one of these IRs is bitcode. From this IR, a program called LLVM takes over and creates the binaries needed for x86 32 and 64 bit modes (for the simulator) and arm6/arm7/arm7s/arm64 (for the device). Normally, all of these different binaries are lumped together in a single file called a fat binary.
> 
> The ENABLE_BITCODE option cuts out this final step. It creates a version of the app with an IR bitcode binary. This has a number of nice features, but one giant drawback: it can't run anywhere. In order to get an app with a bitcode binary to run, the bitcode needs to be recompiled (maybe assembled or transcoded… I'm not sure of the correct verb) into an x86 or ARM binary.
> 
> When a bitcode app is submitted to the App Store, Apple with take on this final step and create the finished binaries.
> 
> Right now, bitcode apps are optional, but history has shown Apple turns optional things into requirements (like 64 bit support). This usually takes a few years, so third party developers (like Parse) have time to update.
> 
> can I use the above method without any negative impact and without compromising a future appstore submission?
> Yes, you can turn off ENABLE_BITCODE and everything will work just like before. Until Apple makes bitcode apps a requirement for the App Store, you will be fine.
> 
> Are there any performance impacts if I enable / disable it?
> There will never be negative performance impacts for enabling it, but internal distribution of an app for testing may get more complicated.
> 
> As for positive impacts… well that's complicated.
> 
> For distribution in the App Store, Apple will create separate versions of your app for each machine architecture (arm6/arm7/arm7s/arm64) instead of one app with a fat binary. This means the app installed on iOS devices will be smaller.
> 
> In addition, when bitcode is recompiled (maybe assembled or transcoded… again, I'm not sure of the correct verb), it is optimized. LLVM is always working on creating new a better optimizations. In theory, the App Store could recreate the separate version of the app in the App Store with each new release of LLVM, so your app could be re-optimized with the latest LLVM technology.

From: http://stackoverflow.com/questions/31088618/impact-of-xcode-build-options-enable-bitcode-yes-no

**Comment by pangweiwei** [comment]
It looks like an automatic mechanism to generate bitcode, what should I support? I think you just copy slua.c to plugins folder instead of slua.a, let xcode compile slua.c to IR code and rebuild for device. 

Am I right?

**Comment by pangweiwei** [comment]
Maybe  I need supply bitcde version of slua.a?

**Comment by heha** [comment]
The error said like below when I tried to build with bitcode enable:

ld: 'XCode/Libraries/Plugins/iOS/libslua.a(slua.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

I guess you may have to supply bitcode version of all .a library. I'm not sure about the process since I never build c library for ios myself but maybe instruction is in below thread:
http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled

**Comment by pangweiwei** [comment]
ok, I will try

**Comment by heha** [comment]
Thank you very much.

**Comment by pangweiwei** [comment]
I found luajit generate final arm native code for lj_vm.o, this object file isn't across-compiled by clang instead of buildvm, so lj_vm can't be link together with other object files generated by clang, so got error information:

ld: -undefined and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

**Comment by pangweiwei** [comment]
if you enable bitcode, should use lua instead of luajit.
