### ISSUE TITLE
Unity 5.3 compatibility issue?

### ISSUE THREAD

**Issue by islet8** [pangweiwei/slua#129]
[Environment: Slua 1.1.1, Unity 5.3.2p1]

When I build Android apk for my project (an almost empty project within SLua, switched to Android platform), I got the following errors:

> Assets/Slua/LuaObject/Unity/LuaDelegate_UnityEngine_WSA_AppCallbackItem.cs(12,74): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
> Assets/Slua/LuaObject/Unity/LuaDelegate_UnityEngine_WSA_WindowActivated.cs(12,74): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
> Assets/Slua/LuaObject/Unity/LuaDelegate_UnityEngine_WSA_WindowSizeChanged.cs(12,74): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?

I've re-generated UnityEngine and UI codes for a couple of times, and tried some other ways but still cannot solve it.
Any ideas? Much appreciated!

JO3L

**Comment by islet8** [comment]
Finally I added two line to CustomExport.OnGetNoUseList() and solved the problem. These two class/namespace are added in Unity 5.3 for WinPhone:
```
				"WSA",
				"EventProvider",
```
JO3L

**Comment by yestein** [comment]
It can works,thank you :)

**Comment by pangweiwei** [comment]
ok, fixed
