### ISSUE TITLE
[request] 能否增加option让Slua禁止使用C#反射模式

### ISSUE THREAD

**Issue by c3076802** [pangweiwei/slua#131]
当一个类没有导出到lua的时候，SLua会自动使用反射模式，有时候开发者忘了导出也能正确执行，虽然说是很方便，但是还是造成了一些效率浪费，尽量static导出，压榨多一些效率，所以我请求，是否可以增加option让SLua禁止使用C#的反射模式

**Comment by pangweiwei** [comment]
现在jiuy这个宏开关

发自我的 iPhone

**Comment by c3076802** [comment]
谢谢，我自己找找。非常感谢

**Comment by c3076802** [comment]
大神，没有找到，请教

**Comment by pangweiwei** [comment]
这个宏 SLUA_CHECK_REFLECTION
