### ISSUE TITLE
LuaTimer 默认的行为是一次性定时器

### ISSUE THREAD

**Issue by youenough** [pangweiwei/slua#136]
现在的实现中，定时器最基本的语义是一次性的，循环的定时器是通过不停的创建新的一次性定时器实现。
这里是不是应该让最基本的定时器是循环的，而一次性的定时器是通过执行一次后 delete 来实现。感觉更符合实际场景一些，而且绝大部分情况下也更高效些。

**Comment by chiuan** [comment]
@youenough 我就不同意了，相反计时器一般都是一次性的，循环的情况比较少

**Comment by youenough** [comment]
@chiuan 引擎的定时器本身的检测频率就不是按最小刻度来的，定时器设定的时间只能假设是不准的。依赖于一次性定时器的我一直都感觉只能用于比较简单的任务。关于延迟执行任务，我们往往不依赖时间而是依赖具体的状态，这样感觉更严谨些，比如延迟多少帧，延迟到进入到某个状态，延迟到某个动画执行到哪个状态（而不是假设这个事情会执行多长时间，然后延迟多长时间执行另外的任务）
如果依赖状态，则只能假定是循环的。我们一般使用 Timer 都是当作可调频度的 Update 使用~
不过也可能是我们使用的范式不同的原因，确实 Linux 内核的定时器都是一次性的。
能麻烦举几个你们使用一次性定时器的场景参考下吗？谢谢了。
