### ISSUE TITLE
Lastest master version has en error in Android, "EntryPointNotFoundException: luaLS_loadbuffer"

### ISSUE THREAD

**Issue by heha** [pangweiwei/slua#141]
"EntryPointNotFoundException: luaLS_loadbuffer" appear when I try to init lua in Android. This working find on release version 1.1.1 but on master, it has an error. Please look into it.

**Comment by pangweiwei** [comment]
// be caurefull here, doBind Run in another thread
			// any code access unity interface will cause deadlock.
			// if you want to debug bind code using unity interface, need call doBind directly, like:
			// doBind(L);
			ThreadPool.QueueUserWorkItem(doBind, L);

comment out doBind(L) and remove "ThreadPool.QueueUserWorkItem(doBind, L);"

let binding work running on main thread.

**Comment by heha** [comment]
Still the same. Not work on Nexus 5.

**Comment by pangweiwei** [comment]
update
