### ISSUE TITLE
协程如何关闭

### ISSUE THREAD

**Issue by youZhuang** [pangweiwei/slua#143]
local c = coroutine.create(function (  )
      Yield(WaitForSeconds(1))
      --这时候gameObject如果已经destroy掉了，会报空指针的错误，有没有办法能把这个协程手动关掉，使协程走不到这里
     gameObject:SetActive(false)
end)
coroutine.resume(c)

**Comment by zjhongxian** [comment]
不改它底层代码，无法关闭。。我是修改了下它的接口，Yield(MonoBehaviour, Enumerator)来实现协程的关闭

**Comment by youZhuang** [comment]
您能说的具体点吗 slua的Coroutine.cs没看太明白 Yield(MonoBehaviour, Enumerator)这个在哪实现的

**Comment by pangweiwei** [comment]
不能关闭，只能自己运行完退出。

在 2016-06-14 11:02:47，"youZhuang" <notifications@github.com> 写道：


您能说的具体点吗 slua的Coroutine.cs没看太明白 Yield(MonoBehaviour, Enumerator)这个在哪实现的
