### ISSUE TITLE
Enum Type 'UnityEngine.CameraClearFlags' generate wrong code 

### ISSUE THREAD

**Issue by tf1379** [pangweiwei/slua#145]
I recently upgraded slua to version 1.1.1, (pre version is 0.7.3).
in lua code below , `flag` got a nil value: 
```cs
local flag = CameraClearFlags.SolidColor
```
---
I found that
`CameraClearFlags.SolidColor` and `CameraClearFlags.Color` are the same value 2

- CameraClearFlags:
```cs
namespace UnityEngine
{
	public enum CameraClearFlags
	{
		Skybox = 1,
		Color,
		SolidColor = 2,
		Depth,
		Nothing
	}
}
```

- but generate code use the same name `Color`
    - Lua_UnityEngine_CameraClearFlags.cs
```cs
using UnityEngine;
using System;
using LuaInterface;
using SLua;
using System.Collections.Generic;
public class Lua_UnityEngine_CameraClearFlags : LuaObject {
	static public void reg(IntPtr l) {
		getEnumTable(l,"UnityEngine.CameraClearFlags");
		addMember(l,1,"Skybox");
		addMember(l,2,"Color");
		addMember(l,2,"Color");
		addMember(l,3,"Depth");
		addMember(l,4,"Nothing");
		LuaDLL.lua_pop(l, 1);
	}
}
```
---
I found that new `RegEnumFunction` code caused this error.  below:
```cs
foreach (object value in Enum.GetValues (t))
{
	Debug.LogWarning(value.ToString());
	Write(file, "addMember(l,{0},\"{1}\");", Convert.ToInt32(value), value.ToString());
}
```
---
So I just revert `RegEnumFunction` to pre version and get the right answer. 
:)

**Comment by pangweiwei** [comment]
@wlgys8 , could you tell my why you modify code? 
https://github.com/pangweiwei/slua/commit/651bd65c2d63dcc3044e7c7784acc63734e0c5f8

**Comment by kakalong** [comment]
@pangweiwei  I think you @  the wrong person, e9552e4 @yongkangchen  simplify iteration of Enum values , this is the commit.

I also encountered this bug , and revert code just works fine.

**Comment by wlgys8** [comment]
应该不是我的锅吧？

**Comment by pangweiwei** [comment]
fixed
