### ISSUE TITLE
Color32 in C# can't export to lua

### ISSUE THREAD

**Issue by Magicqy** [pangweiwei/slua#149]
// in C# script
> [CustomLuaClass]
public class HelloWorld
{
    public Color32 c32;
    public Color c;
}

-- in lua script
> local hw = HelloWorld()
hw.c = UnityEngine.Color(1,1,1,1)
print(hw.c)
hw.c32 = UnityEngine.Color32(1,1,1,1)
print(hw.c32)

hw.c32 = UnityEngine.Color32(1,1,1,1) will get an exception

> [string "..."]:4: System.NullReferenceException: Object reference not set to an instance of an object
  at SLua.LuaObject.checkValueType\[Color32\] (IntPtr l, Int32 p, UnityEngine.Color32& v) [0x00000]

**Comment by pangweiwei** [comment]
fixed
