### ISSUE TITLE
崩溃问题，非必现

### ISSUE THREAD

**Issue by yongkangchen** [pangweiwei/slua#151]
![c550ffdf0f8917e9b7cc832674476236](https://cloud.githubusercontent.com/assets/704762/16836404/f4adac44-49ef-11e6-88c0-0df006559b0d.png)

**Comment by yongkangchen** [comment]
阅读了lua5.1的lua_pushcclosure函数源码，没有找到调用lua_error的代码以及原因。那么初步怀疑是这个coredump的堆栈信息已经混乱了

**Comment by yongkangchen** [comment]
据反馈：
> 关于上次 lua_pushcclosure 位置发生的崩溃，我们编译了调试版的slua,后来捕获到了清晰的调用栈
> 出错原因是memory not enough
```
err_raise_ext 443
lj_err_throw 458
lj_err_mem 494
lj_mem_newgco 828
lj_func_newC 109
lua_pushcclosure 628
```

**Comment by pangweiwei** [comment]
这是上次那个编辑器导致OOM的问题？还是你们自己导致的OOM？

**Comment by pirunxi** [comment]
编辑器里

**Comment by pangweiwei** [comment]
嗯，编辑器有个内存泄漏的问题，因为反复启动，导致object不能回收，需要频繁重启编辑器，发布的app不会有这个问题，之前修复过这个问题，你们更新没？
