### ISSUE TITLE
delegate造成的对象无法释放的问题

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#156]
比如有一个button.

lua代码:

local button = Loadbutton();
button.onClick:AddListener(function(){
     button.name = 'test' --注释掉这句代码则可以正常回收button对象
})
GameObject.Destroy(button.gameObject)

这个时候即使把button对象destroy了，然后执行lua gc。也无法回收button对象。 
通过观察c#的ObjectCache，可以发现这个button对象一直在freelist里面而没有被回收掉

**Comment by wlgys8** [comment]
监控LuaState里的delegateMap,发现 UnityAction 的 weak reference一直处于Alive状态。
但是button已经destroy了，应该没引用了呀？
所以是UnityAction引用button,但是button又引用了UnityAction的原因？

**Comment by wlgys8** [comment]
1.newDelegate 中，luaL_ref 引用住了 lua中 function
2.lua中的function引用住了c#的object
3.c#的object引用住了LuaDelegate(从而不会执行dispose,释放lua中的function)

从而形成循环引用，c#和lua各自的gc系统都无法进行回收?

**Comment by pangweiwei** [comment]
delegate需要-=啊，你有没有做？

**Comment by wlgys8** [comment]
那只能手动在onDestroy的时候清除一下delegate吧。。
想了下 两个独立的gc系统还是处理不了这种循环引用的问题

**Comment by wlgys8** [comment]
这样的话 有一些写法实际上就必须避免了，比如:

local asyncOp = object:LoadAsync()
asyncOp.onCompleted = function()
   object:doSomething()
end

这样asyncOp这个临时变量就会永远得不到释放

为了保证能够正常GC,写法就要改成:
local asyncOp = object:LoadAsync()
asyncOp.onCompleted = function()
   object:doSomething()
   asyncOp.onCompleted = nil  --加入这一句
end

觉得也算一个坑吧。

**Comment by wlgys8** [comment]
我想给ObjectCache加个统计的接口，分析是否有对象泄露。

这个稍不注意，还是很容易导致ObjectCache越来越大的。
对于lua的使用者来说，他必须清楚哪些function 是注册到c#对象上的，这种function必须在c# 对象销毁的时候 同步remove掉。（写习惯了闭包的一般不会这么做。。）

然后MonoBehaviour的OnDestroy也有些坑..没有active过的Object上的脚本不会调用OnDestroy..

感觉这一块使用上并不是那么傻瓜式，应该会有很多人踩这个坑

**Comment by humansprite** [comment]
@wlgys8 
实践中发现最好的解决方法就是在lua实例生命周期结束的时候，把这个实例所有键值对清除，就可以避免lua跟c#之间的循环引用。
