### ISSUE TITLE
Generate code under System namespace

### ISSUE THREAD

**Issue by evepoe** [pangweiwei/slua#16]
Hi,

In the OnAddCustomClass I added the following:
list.Add(typeof(System.IO.Directory)); 

But the code generated has a lot of compilation errors. The same happens to a lot of other classes under System as well. 

A workaround is to write some custom wrapper class calling into those system classes, but a working native support would awesome.

**Comment by pangweiwei** [comment]
I think you should switch Api compatibility level to ".net 2.0" instead of ".net 2.0 subset" from player settings.

**Comment by evepoe** [comment]
Thank you, it's working like a charm.
