### ISSUE TITLE
默认Loader实现中将文件路径中的.替换为/是否合理？

### ISSUE THREAD

**Issue by Magicqy** [pangweiwei/slua#173]
默认的Loader方法实现位于LuaState.cs中的loadFile方法，其中将路径参数做了替换：fn = fn.Replace(".", "/");
这将导致require时，同一个文件有很多种写法，虽然内容完全相同，但重复加载执行，占用内存。
例如：
local v1 = require('path.of.file')
local v2 = require('path/of/file')
v1 == v2 --false

**Comment by pangweiwei** [comment]
默认的实现就是简单的示范，无法运用于实际游戏环境，需要自行按照需求修改。
