### ISSUE TITLE
多luastate捕获异常

### ISSUE THREAD

**Issue by tuyazuo** [pangweiwei/slua#176]
想用slua standalone做服务器，会开多个luastate，但发现多开后，其他的luastate中lua代码的异常信息没法被dubug出来

**Comment by pangweiwei** [comment]
我会修复这个问题。


原始邮件
发件人:tuyazuonotifications@github.com
收件人:pangweiwei/sluaslua@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年3月25日(周六) 17:04
主题:[pangweiwei/slua] 多luastate捕获异常 (#176)


想用slua standalone做服务器，会开多个luastate，但发现多开后，其他的luastate中lua代码的异常信息没法被dubug出来
