### ISSUE TITLE
Can't have negative indices (or index 0)

### ISSUE THREAD

**Issue by ratkingsminion** [pangweiwei/slua#180]
Although it is possible in Lua to have tables with negative indices, like so:
`local myTable = { [-3] = "foo", [-1] = "bar" }`
it is not possible with SLua to easily get the value of myTable[-3], because LuaState.getObject() (line 1022) throws IndexOutOfRangeException if the index is smaller than 1.

**Comment by pangweiwei** [comment]
ok, I will fix

**Comment by pangweiwei** [comment]
fixed
