### ISSUE TITLE
UnityEngine.Vector2 不能获取

### ISSUE THREAD

**Issue by Yangzhengyi** [pangweiwei/slua#181]
环境:　ubuntu.
untiy:  5.5.2f1.
 
读取UnityEngine.Vector2．up时，得到table: 0x94b859c2880．　而不是预期的vector{ }.
UnityEngine.Vector3．up是正常的．

**Comment by pangweiwei** [comment]
不是很明白什么意思?

**Comment by Yangzhengyi** [comment]
我在ubuntu是跑untiy editor.运行我的项目的时候，我代码需要需要获取UnityEngine.Vector2．up的值，但是返回的内容却不是vector{1,0}而是一个不认识的table: table: 0x94b859c2880.

**Comment by pangweiwei** [comment]
详细描述你的问题，lua代码如何写，得到什么输出，mac、win上又这个问题吗？输出到手机上又这个问题吗？
