### ISSUE TITLE
LuaDelegation调用checkDelegate错误

### ISSUE THREAD

**Issue by GuipengLiao** [pangweiwei/slua#197]
UnityEngine.Collections.DisposeSentinel.DeallocateDelegate在unity5.6版本中被改为private,导致lua无法直接调用,需要使用DisposeSentinel.Create(IntPtr ptr, Allocator label, int callSiteStackDepth, DisposeSentinel.DeallocateDelegate deallocateDelegate = null)来创建DisposeSentinel对象,然后通过DisposeSentinel.DisposeSentinel来获取DisposeSentinel对象..

但是我不知道怎么使用DisposeSentinel.Create()方法,故求助值之

**Comment by pangweiwei** [comment]
已经fix了，没有release而已

**Comment by pangweiwei** [comment]
参考 https://github.com/pangweiwei/slua/commit/857a4771de569883d15eef79d16314fa24a9b8b6
