### ISSUE TITLE
5.6.1f 里面gen没问题，但是编译的时候就出问题。

### ISSUE THREAD

**Issue by amyvmiwei** [pangweiwei/slua#199]
Assets/Slua/LuaObject/Unity/Lua_UnityEngine_Collections_NativeLeakDetection.cs(11,44): error CS0234: The type or namespace name `NativeLeakDetection' does not exist in the namespace `UnityEngine.Collections'. Are you missing an assembly reference?
Assets/Slua/LuaObject/Unity/Lua_UnityEngine_Collections_NativeLeakDetection.cs(22,28): error CS0234: The type or namespace name `NativeLeakDetectionMode' does not exist in the namespace `UnityEngine.Collections'. Are you missing an assembly reference?
Assets/Slua/LuaObject/Unity/Lua_UnityEngine_Collections_NativeLeakDetection.cs(23,22): error CS0841: A local variable `v' cannot be used before it is declared
Assets/Slua/LuaObject/Unity/Lua_UnityEngine_Collections_NativeLeakDetection.cs(23,4): error CS0453: The type `<error>' must be a non-nullable value type in order to use it as type parameter `T' in the generic type or method `SLua.LuaObject.checkEnum<T>(System.IntPtr, int, out T)'
。。。。
等11处错误。

**Comment by pangweiwei** [comment]
谢谢反馈，已经修复
