### ISSUE TITLE
Starting a 2nd Lua Server (sandboxed) 

### ISSUE THREAD

**Issue by igniuss** [pangweiwei/slua#205]
Is it possible to create a 2nd LuaSvr, with everything sandboxed? (no c# classes, only basic math/string api).
If so, how would this be achieved? 

Loving this repo btw, runs extremely fast 👍 

_edit:_ if this isn't easily possible, I can always just insert a sandbox script in the main stack, and load it using ``table = luaState.doString("return dofile(path)")``, but would prefer to not go down that road 😅

**Comment by pangweiwei** [comment]
yes , you can create 2nd luaState without any c# class, see multistate demo in Ver1.5
