### ISSUE TITLE
如何在Slua中使用Vector3数组

### ISSUE THREAD

**Issue by YoungGG0101** [pangweiwei/slua#208]
本人刚接触Slua不久，在lua中调用C#接口时需要传Vector3数组的参数，不知道需要怎样设置才可以将vector3的线性表转化成vector3数组，https://github.com/pangweiwei/slua/issues/67 在采用67中的解决方案加入checkType与checkParam后仍然无法使用vector3[]。希望能获得一个详细的解答

**Comment by pangweiwei** [comment]
like this setFunction({Vector3(1,1,1),Vector3(0,0,0),Vector3(2,2,2)})
