### ISSUE TITLE
2017.2 导出问题

### ISSUE THREAD

**Issue by zhushaojun65** [pangweiwei/slua#209]
pang总你好, 今天更新unity2017.2, Lua导出脚本出现很多错误, 重新编译之后, 很多接口都没有了, 能帮忙看一下吗?

**Comment by pangweiwei** [comment]
我调试了一下，要原因 对于UnityEngine，assembly.GetExportedTypes() 返回了空数组，导致找不到任何可以导出的类型，接口就丢失了，不知道这个是bug还是unity有意为之。

**Comment by pangweiwei** [comment]
fix了
