### ISSUE TITLE
luaOp可能存在的堆栈错误

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#216]
目前这个bug发生的情况是这样的:
lua代码里执行:

	local span = DateTime.UtcNow - DateTime(1970,1,1)

正常情况下，这个减法返回的应该是一个TimeSpan类型。但在某种情况下，这里返回了一个DateTime类型，而且返回值 =  DateTime(1970,1,1)，也就是减法的第二个参数。

通过对LuaObject中的 

		static int luaOp(IntPtr l, string f, string tip)
		{
			Debug.LogFormat ("top:{0},{1}" ,l,LuaDLL.lua_gettop(l));
			int err = getOpFunction(l, f, tip);
			LuaDLL.lua_pushvalue(l, 1);
			LuaDLL.lua_pushvalue(l, 2);
			if (LuaDLL.lua_pcall (l, 2, 1, err) != 0) {
				LuaDLL.lua_pop (l, 1);
			}
			Debug.Log ("error:" + f+":"+err);
			LuaDLL.lua_remove(l, err);
			pushValue(l, true);
			LuaDLL.lua_insert(l, -2);
			return 2;
		}

这个函数打印日志发现:
正常情况下，getOpFunction返回的err是2，而在异常情况下err是3.

且注释掉

			LuaDLL.lua_remove(l, err);
这句代码，则一切就正常了。

怀疑当err是3的时候，这个地方remove掉了正常的返回值，导致lua里取到的返回值不对。

**Comment by wlgys8** [comment]
发现err function是被压在 __main_state上的，但是这里却在函数的 state上remove它.

**Comment by wlgys8** [comment]
难道 #214 里提到的crash也是因为这个err func引起的。。
lua_pcall 传入的 err实际上并不存在于函数栈上，当pcall出错的时候，直接挂了

**Comment by pangweiwei** [comment]
正常情况下，err保存的是error出来函数，栈上分别是
对应的op函数
操作数1
操作数2
if (LuaDLL.lua_pcall (l, 2, 1, err) != 0) 这一行调用后，栈上会弹出op函数，和2个参数，同时返回一个值，栈上应该是err+1个值，
最后remove掉err，栈上就只有返回值，最后push true，表示函数调用成功，同时和返回值交换一下位置。

以上是正常逻辑，不知道你给的测试用例是不是100% 出错？

**Comment by pangweiwei** [comment]
你存在多个state吗，或者是coroutine里？

**Comment by wlgys8** [comment]
我没有用多个state,不过的确是在coroutine里调用的。

当`static int luaOp(IntPtr l, string f, string tip)`参数里的IntPtr l 不等于 __main_state的时候会引发这个bug

		public static int pushTry(IntPtr l)
		{
            var state = LuaState.get(l);
            if (!state.isMainThread())
			{
				Logger.LogError("Can't call lua function in bg thread");
				return 0;
			}

            return state.pushTry();
		}

这个调用里 `LuaState.get(l)` 是把err函数压入到__main_state上的
但是op函数是在另一个栈上执行

**Comment by pangweiwei** [comment]
ok 我稍后修复
