### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by igniuss** [pangweiwei/slua#217]
We're using Lua quite extensively in our application, and are experiencing some ``out of memory`` exceptions, usually around 8mb of garbage. 

Any way we can increase this limit?

**Comment by pangweiwei** [comment]
what is your version?

**Comment by igniuss** [comment]
I believe I'm running ``9f3a99db7619676f2b95a4d7449a409cffba2d48``
It seems to be happening when the process in total is getting around 2GB of memory (can't believe I didn't notice this earlier, sorry about that).

I'll update to the latest released version, and see if that helps

**Comment by wlgys8** [comment]
i also get `no enough memory` error in unity editor sometimes.

**Comment by pangweiwei** [comment]
latest slua build with luajit2.1, it limit memory can't over 2GB, you can build slua with lua5.1 or lua5.3, there is no limit.

**Comment by pangweiwei** [comment]
you also can use old version like 1.3, it build with lua 5.1, no memory limit

**Comment by pangweiwei** [comment]
you can see $slua$/build folder, there are many build scripts for different platforms.

**Comment by pangweiwei** [comment]
this repo is prebuilt library for lua5.3 https://github.com/yaukeywang/slua-503-build

**Comment by igniuss** [comment]
Thanks for the explanation!
