### ISSUE TITLE
Custom ValueType returning as UserData

### ISSUE THREAD

**Issue by igniuss** [pangweiwei/slua#218]
Hi, I've been trying to implement some custom valueTypes we use in our game (double classes for Vector, Mathf, and Matrixes) and have already implemented the lua override for it in [LuaValueType.cs](https://github.com/pangweiwei/slua/blob/7667f82bffd7abd4ac96ec34f76e01fe4ba85009/Assets/Plugins/Slua_Managed/LuaValueType.cs).

Instantiating the types in lua works just as expected, but returning the value from a c# source does not return it as a table, but userData. 

Is there any way I can force the return from C# to be a table instead of userData? 

Thanks.

**Comment by pangweiwei** [comment]
yes, you can find a function like:

public static void pushValue(IntPtr l, Vector3 o)
		{
			LuaDLL.luaS_pushVector3(l, o.x, o.y, o.z);
		}

luaS_pushVector3 push vector3 as table ,you should add overload function to push your value type as table.
