### ISSUE TITLE
Catching of exceptions in Lua

### ISSUE THREAD

**Issue by kotrs** [pangweiwei/slua#219]
Hello, 
how can I catch exception in Lua ? The Unity Editor crash when the exception is in Lua.

Unity 5.5.1f
SLua 1.5.2

Thank you

**Comment by pangweiwei** [comment]
could you give me traceback of exception?

**Comment by kotrs** [comment]
This is the problem. I don't know how can I get traceback of exception. When I run game with bad syntax in lua (for example) then Unity crashes and I have to start all Unity again.
