### ISSUE TITLE
byte[]参数类型匹配是否有误

### ISSUE THREAD

**Issue by lessball** [pangweiwei/slua#226]
LuaObject.matchType里把byte[]匹配到lua string，直接传数组反而匹配失败。暂时去掉这几行解决了问题。

https://github.com/pangweiwei/slua/blob/0f935b04203212016174fc1dc9e03c74c3629ec6/Assets/Plugins/Slua_Managed/LuaObject.cs#L673

**Comment by lessball** [comment]
lua调用unity WWW构造函数
local www = WWW(url, postData)
c#原型：
public WWW(string url, byte[] postData);
lua调用其它c#方法返回的byte[]，传给postData，匹配失败。slua 1.5.2 release版。暂时把673-676行去掉解决。

**Comment by pangweiwei** [comment]
我已经修复了，这样修改：
else if (t == typeof(char[]) || t==typeof(byte[]))
			{
				return lt == LuaTypes.LUA_TSTRING || lt == LuaTypes.LUA_TUSERDATA;
			}
