### ISSUE TITLE
luaTypeCheck问题

### ISSUE THREAD

**Issue by qiankanglai** [pangweiwei/slua#231]
https://github.com/pangweiwei/slua/blob/master/Assets/Plugins/Slua_Managed/LuaObject.cs#L704

在使用DOTween的时候 transform:DOScale(1.0, 1.0)没问题，但transform:DOScale(Vector3(1,1,1), 1.0)会报错。

原因是检查matchType的时候DOScale(Vector3, float)会满足第一个if导致进错重载函数了...

			if(matchType(l,argc,2,typeof(float),typeof(float))){
				UnityEngine.Transform self=(UnityEngine.Transform)checkSelf(l);
				System.Single a2;
				checkType(l,2,out a2);
				System.Single a3;
				checkType(l,3,out a3);
				var ret=self.DOScale(a2,a3);
				pushValue(l,true);
				pushValue(l,ret);
				return 2;
			}
			else if(matchType(l,argc,2,typeof(UnityEngine.Vector3),typeof(float))){
				UnityEngine.Transform self=(UnityEngine.Transform)checkSelf(l);
				UnityEngine.Vector3 a2;
				checkType(l,2,out a2);
				System.Single a3;
				checkType(l,3,out a3);
				var ret=self.DOScale(a2,a3);
				pushValue(l,true);
				pushValue(l,ret);
				return 2;
			}

我把注释里的luaTypeCheck打开 看起来没问题了，查了下历史提交是optimize code 不知道有没有其他影响

**Comment by pangweiwei** [comment]
可以打开，注释掉，只是提高速度。
