### ISSUE TITLE
unity2017.4.1 移动平台编译不过

### ISSUE THREAD

**Issue by SimonneX** [pangweiwei/slua#232]
Assets/Slua/LuaObject/Unity/Lua_UnityEngine_Texture.cs(401,21): error CS1061: Type `UnityEngine.Texture' does not contain a definition for `imageContentsHash' and no extension method `imageContentsHash' of type `UnityEngine.Texture' could be found. Are you missing an assembly reference?

unity文档中 Note that the hash is an Editor-only property.
https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Texture-imageContentsHash.html

**Comment by pangweiwei** [comment]
你可以加入过滤列表里，具体看https://github.com/pangweiwei/slua/blob/master/help.md#%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%87%BA
