### ISSUE TITLE
AudioSource 没有导出接口

### ISSUE THREAD

**Issue by zhushaojun65** [pangweiwei/slua#235]
你好, 今天开始做游戏音效, 发现UnityEngine.AudioSource这个类竟然没有导出接口, NoUseList中也没有设置这个类, 能帮忙看一下吗?

注: Unity版本号 2017.3.1f1

暂时我通过Custom导出来解决问题

**Comment by zhushaojun65** [comment]
LuaCodeGen.cs
`#if UNITY_2017_2_OR_NEWER
        public static string[] unityModule = new string[] { "UnityEngine","UnityEngine.AudioModule","UnityEngine.CoreModule","UnityEngine.UIModule","UnityEngine.TextRenderingModule","UnityEngine.TextRenderingModule",
                "UnityEngine.UnityWebRequestWWWModule","UnityEngine.Physics2DModule","UnityEngine.AnimationModule","UnityEngine.TextRenderingModule","UnityEngine.IMGUIModule","UnityEngine.UnityWebRequestModule",
            "UnityEngine.PhysicsModule", "UnityEngine.UI" };
#else
        public static string[] unityModule = null;
#endif`

module中少了模块 UnityEngine.AudioModule

**Comment by pangweiwei** [comment]
ok，fix ASAP
