### ISSUE TITLE
unity 2018 .net 版本改成4.x之后的绑定文件导出有问题

### ISSUE THREAD

**Issue by jerusalemdax** [pangweiwei/slua#241]
![qq 20180720175806](https://user-images.githubusercontent.com/1510187/42996599-9fae77e6-8c46-11e8-8fef-b13bbc8cb808.png)

有些诡异，有些类的构造函数多了几个，并且无法被识别。比如Dictionary<int, string> 多了两个IEnumerator为参数的构造函数，但是实际上Dictionary并无这两个构造函数。

**Comment by pangweiwei** [comment]
删除了，重新导出

**Comment by pangweiwei** [comment]
你是使用4.x的.net的运行时？

**Comment by pangweiwei** [comment]
目前4.x的.net运行时不支持，之前我测试过，发现很多莫名其妙的语法错误，没有时间仔细看

**Comment by pangweiwei** [comment]
fix了，请pull更新。
