### ISSUE TITLE
Slua.out功能报错

### ISSUE THREAD

**Issue by jerusalemdax** [pangweiwei/slua#247]
![qq 20181006110745](https://user-images.githubusercontent.com/1510187/46566813-4d8a1480-c958-11e8-902b-1f6924be84f0.png)

Slua 1.6.0 out 参数功能报错
直接运行example main场景就可以出现
貌似是LuaCodeGen.cs的 IsOutArg函数有问题

**Comment by pangweiwei** [comment]
fix
