### ISSUE TITLE
 slua/Assets/Plugins/Slua_Managed/LuaState.cs文件1675～1679行未针对Standalone做判断处理

### ISSUE THREAD

**Issue by shh12580** [pangweiwei/slua#249]
问题文件： slua/Assets/Plugins/Slua_Managed/LuaState.cs
问题行：1675～1679行           
问题：Standalone模式下引用UnityEngine会出错，需要做判断处理 
出错代码：regPushVar(typeof(UnityEngine.Vector2), (IntPtr L, object o) => { LuaObject.pushValue(L, (UnityEngine.Vector2)o); });
            regPushVar(typeof(UnityEngine.Vector3), (IntPtr L, object o) => { LuaObject.pushValue(L, (UnityEngine.Vector3)o); });
            regPushVar(typeof(UnityEngine.Vector4), (IntPtr L, object o) => { LuaObject.pushValue(L, (UnityEngine.Vector4)o); });
            regPushVar(typeof(UnityEngine.Quaternion), (IntPtr L, object o) => { LuaObject.pushValue(L, (UnityEngine.Quaternion)o); });
            regPushVar(typeof(UnityEngine.Color), (IntPtr L, object o) => { LuaObject.pushValue(L, (UnityEngine.Color)o); });

**Comment by pangweiwei** [comment]
感谢反馈

**Comment by pangweiwei** [comment]
fix
