### ISSUE TITLE
Can't access lua in bg thread 如何解决?

### ISSUE THREAD

**Issue by BurgerKingW** [pangweiwei/slua#250]
unity版本 2018.2.14f
slua是最新版本

**Comment by pangweiwei** [comment]
这个问题说明，你在后台线程访问了slua的api，比如异步socket的回调函数就会在另外一个线程，slua不支持跨线程访问lua，所以你需要修改你的代码，避免在后台线程调用slua api。
这是一种安全的检查机制，避免你莫名其妙出现crash等不好查的问题。
