### ISSUE TITLE
Unity crash when trying to get UnityEngine.Color.Instance

### ISSUE THREAD

**Issue by ratkingsminion** [pangweiwei/slua#254]
The following code crashes Unity (2018.2.15) on the second line:

`var _g = luaState["_G"] as SLua.LuaTable;`
`var color = _g["UnityEngine.Color.Instance"];`

luaState is a correctly initialized Slua.LuaState.

**Comment by pangweiwei** [comment]
LuaTable.getObject(same as []) will split passed key string by '.' to path list， luatable use the path-list to find value step by step, but UnityEngine.Color don't have a key named Instance, so report a error.

slua use ""UnityEngine.Color.Instance" as whole key to store instance method table.

**Comment by ratkingsminion** [comment]
The thing is that it's okay if I just iterate over _G's objects via ´foreach (var kvp in _g)`, but when I iterate over all the keys via a list later, Unity crashes, and that shouldn't happen IMHO.

**Comment by pangweiwei** [comment]
I add 2 function get/set key from/to table.

**Comment by pangweiwei** [comment]
I also add rawget/set flag for get/set functions.
