### ISSUE TITLE
How to import UnityEngine namespace when making-UnityEngine is edited by Unity

### ISSUE THREAD

**Issue by zhengxianyangZZ** [pangweiwei/slua#255]
我在 making-UnityEngine之后会出现报错，缺少UnityEngine命名空间。手动添加的话会太多，很麻烦。求解决办法。Unity版本5.3.8f1
After making-UnityEngine, I get an error and lack the UnityEngine namespace. It's too much to add manually. It's troublesome. Find solutions. Unity version 5.3.8f1

**Comment by zhengxianyangZZ** [comment]
slua version v1.6.0 Release

**Comment by pangweiwei** [comment]
你需要import "UnityEngine"
