### ISSUE TITLE
slua lua的方法传递给C#会造成内存泄漏吗？

### ISSUE THREAD

**Issue by tianjiuwan** [pangweiwei/slua#257]
![image](https://user-images.githubusercontent.com/17354596/51222210-b598bf80-1977-11e9-80b1-6156cc9364f1.png)

**Comment by pangweiwei** [comment]
你需要Remove delegate

**Comment by pangweiwei** [comment]
只要对应c#变量被置空，对应lua funciton会被回收，但这个回收不是立刻的，需要等待c#和lua的gc
