### ISSUE TITLE
Android arm64-v8a support

### ISSUE THREAD

**Issue by fang8623341** [pangweiwei/slua#272]
作者您好！
    我根据工程编译了一个能正常运行的64位libslua.so文件，不确定是否能稳定的运行。另外，在脚本中有一行代码因为不了解相关的知识，不清楚应该怎么配置。
   在make_android.sh脚本中NDKARCH="-march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8"。希望能得到您的解答与帮助。
   另外，期待您能抽空更新下，官方支持Android arm64-v8a。
   感谢您的分享。

**Comment by chsqn** [comment]
@fang8623341 你好
由作者 @pangweiwei 释出的1.7.0看来 他没打算支持LuaJIT arm64
我找到了一个博客如下
https://blog.csdn.net/eclipse_c/article/details/92774618
你要不要把编译好的libslua.so放到下面这个目录试试
Plugins/Android/libs/armeabi-arm64

**Comment by chsqn** [comment]
或許我們應該更新LuaJIT的https://github.com/LuaJIT/LuaJIT/pull/359
```
https://forum.cocos.com/t/luajit-android-arm64/81417
```
并且參考NDKABI=21编译出Assets/Plugins/Android/libs/armeabi-arm64/libslua.so
```
https://github.com/rampantpixels/lua_lib/blob/master/lua/luajit/build-android.sh
```
再加上mac和win的luajit来产生64位元的bytecode

**Comment by pangweiwei** [comment]
目前的问题是，不是编译支持arm64的问题，之前的build脚本就已经支持arm64了
是实际线上使用arm64的luajit，稳定性不够，我们有对比数据，同样的代码，luajit arm64的crash概率更高，已经实际影响产品质量了。

当然如果大家非常希望恢复arm64 的支持，同时luajit也有进一步更新，我也可以在下个版本把它加回来

**Comment by chsqn** [comment]
如果稳定度是一样的 选用LuaJIT是因为速度和加密 选用原生Lua是因为新版的语言特色 与新版的语言特色比较起来 速度与加密因该是目前多数人的选择

**Comment by fang8623341** [comment]
首先，感谢回复！ 
@chsqn 我已经用之前生成的so文件，对游戏进行了64位的支持了，并通过了谷歌审核。首测的期间暂时未发现异常。后续再试试你提供的方法进行编译。

@pangweiwei 希望支持arm64的原因，是由于谷歌要求8月后提审的应用都需要支持。否则，不能通过审核。目前要出海的新应用都需要支持。

**Comment by yongkangchen** [comment]
> 我们有对比数据，同样的代码，luajit arm64的crash概率更高，已经实际影响产品质量了。

我一直使用的luajit arm64，有几年了，crash概率很小。

@pangweiwei 数据和测试代码能分享给我吗？我有空查一下

**Comment by yongkangchen** [comment]
@pangweiwei 看错。我用的ios arm64。安卓arm64没搞过。不过还是可以发我查查😁

**Comment by pangweiwei** [comment]
> @pangweiwei 看错。我用的ios arm64。安卓arm64没搞过。不过还是可以发我查查😁

iOS arm64 根本就不进行jit😁
