### ISSUE TITLE
更新到slua v1.7.0 Release遇到一种与以前版本不一样的情况

### ISSUE THREAD

**Issue by Oright** [pangweiwei/slua#277]
脚本1用for循环调用脚本2里面包含“string.format("xxxx",arg1,arg2) arg1参数为nil”的方法，脚本2停止执行，脚本1的for不会继续循环下去，脚本1for后面的代码也不会执行，没有报错提示。
就是这两天更新到slua v1.7.0 Release版本，发现有的功能不正常了
ps：以前的slua版本遇到这样的情况能正常运行

**Comment by Oright** [comment]
脚本1for后面的代码也不会执行

**Comment by Oright** [comment]
添加描述：发现不止string.format参数有nil时会出现，现在我故意在一些脚本调用一下不存在的接口，是不会输出报错提示的，只会终止执行。（在个别脚本调用会输出报错提示，但是在其他一些脚本不会输出报错提示）

**Comment by Oright** [comment]
能不能给点反馈，再拖项目要黄了

**Comment by pangweiwei** [comment]
你是不是把错误输出给重载掉了，错误输出 默认 是不会出问题的，你可以测试一下自带的demo会不会有问题。
比如，如果你卸载pcall的里的代码，出了错误，也不会报告，因为被你自己截获了。

**Comment by Oright** [comment]
> 你是不是把错误输出给重载掉了，错误输出 默认 是不会出问题的，你可以测试一下自带的demo会不会有问题。
> 比如，如果你卸载pcall的里的代码，出了错误，也不会报告，因为被你自己截获了。

您好~我这边找到原因了，是这样的LuaState.errorReport中输出报错时，调用到了__tostring方法，我们里面有string.format("LUIView %s isUnInit:%s", o:GetName(), o.isUnInit)，新版的sLua似乎%s赋值布尔值（或nil）会报错（以前用的版本没遇到这样的情况），所以在打印报错时报错了，一直循环，报错最后没打印出来。

**Comment by pangweiwei** [comment]
新的版本移除了jit，可能以前jit是支持为nil的变量tostring的
