### ISSUE TITLE
Does not compile due to two errors.

### ISSUE THREAD

**Issue by Shark-vil** [pangweiwei/slua#287]
Error 1:
`Assets\Slua\LuaObject\Unity\Lua_UnityEngine_Rendering_RenderPipelineAsset.cs(21,21): error CS1061: 'RenderPipelineAsset' does not contain a definition for 'terrainBrushPassIndex' and no accessible extension method 'terrainBrushPassIndex' accepting a first argument of type 'RenderPipelineAsset' could be found (are you missing a using directive or an assembly reference?)
`
![U7AOEIppET](https://user-images.githubusercontent.com/13109606/67288811-42177600-f4e6-11e9-9aa2-27166b8628ca.png)
![devenv_BRX42U2j71](https://user-images.githubusercontent.com/13109606/67288906-64a98f00-f4e6-11e9-8f82-5ccd3423a995.png)
Error 2:
`Assets\Slua\LuaObject\Unity\Lua_UnityEngine_Rendering_ScriptableRenderContext.cs(796,50): error CS0117: 'ScriptableRenderContext' does not contain a definition for 'EmitWorldGeometryForSceneView'
`
![fBWDfkLdC2](https://user-images.githubusercontent.com/13109606/67288919-6d9a6080-f4e6-11e9-86b2-a09a18f881dc.png)
![devenv_y5qkHc1iOv](https://user-images.githubusercontent.com/13109606/67288929-712de780-f4e6-11e9-81d0-89cb29b56939.png)

How to solve a problem? Everything works if you comment on these lines, but they are not considered obsolete, so I don’t understand what the mistake is.

**Comment by Shark-vil** [comment]
In order for the compilation to work, I commented out these lines, because I do not use them anyway. But I ran into another problem. After compilation, the scripts stop working, they simply do not execute, but everything is fine in the editor.

**Comment by Shark-vil** [comment]
And one more question. This is true, not entirely related to the problem. Can I do a dynamic script update? For example, in one LuaState change the code several times when the game is already running.

**Comment by Shark-vil** [comment]
Oh, just in case. My version of the engine is 2019.1.10f1

**Comment by pangweiwei** [comment]
"Can't access lua in bg thread" - How to update the code in the current thread?

post a msg to main thread from
 bg thread, you just handle msg in main thread.

**Comment by pangweiwei** [comment]
I will test code in new untiy version ASAP

**Comment by Shark-vil** [comment]
> "Can't access lua in bg thread" - How to update the code in the current thread?
> 
> post a msg to main thread from
> bg thread, you just handle msg in main thread.

Yes, only recently I noticed that FileSystemWatcher is working in a different thread. It would be nice to actually include script listening in the standard build.

**Comment by Shark-vil** [comment]
> I will test code in new untiy version ASAP

Found a funny thing. I thought the problem is access rights, or doesn’t find the files at all, therefore it does not include them. I created a script for logging to a file, compiled the project and looked at the result. Judging by the log, there are no errors, it finds and initializes files, but this does not manifest itself in the game. But everything works in the engine editor. 

Strange, what's the problem. I already cry without knowing what the problem is :D 
I need an interpreted language for the exam, and your module at least somehow works, unlike others.

**Comment by pangweiwei** [comment]
What's your version of slua? I had test lastest version , no problem you reported.

**Comment by Shark-vil** [comment]
> What's your version of slua? I had test lastest version , no problem you reported.

I downloaded the project from the current git, and tried to run examples of scenes without changes. Need to install something else?

**Comment by pangweiwei** [comment]
fixed
