### ISSUE TITLE
Unity 2017.4.30f1

### ISSUE THREAD

**Issue by Echoflyer** [pangweiwei/slua#289]
Archive的时候报错，Libraries/Plugins/iOS/libslua.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64

**Comment by pangweiwei** [comment]
xcode早都不支持 armv7的编译支持了，新的iphone也不支持了，现在上架应用估计armv7都审核不通过了，你如果需要发行老版本的ios，使用老的slua版本。
