### ISSUE TITLE
String conversion error: Partial byte sequence encountered in the input. Unity 2019.3.3f1

### ISSUE THREAD

**Issue by hottestchilipepper** [pangweiwei/slua#300]
In Unity 2019.3.3f1, when I play a scene with LuaSvr.start(), there is an error that 'String conversion error: Partial byte sequence encountered in the input' at LuaDLL.cs:550.
I have put try catch phrase at this line to go to next 'fallback method', it shows 'Common/Stack:1: unexpected symbol near '�''.
My lua script, 'Common/Stack', is formatted by UTF-8 with BOM. So I have resaved it UTF-8( without BOM ). So the problem has gone.
Before I update the Unity to 2019.3.3f1, I used 2018.2.1f1, there are no problems.
Please check about this issue. Thank you

**Comment by pangweiwei** [comment]
lua parser doesn't support utf-8 with bom
