### ISSUE TITLE
windows 64bit Lua 5.3, unity crash when using table after calling a coroutine.

### ISSUE THREAD

**Issue by yaukeywang** [pangweiwei/slua#35]
Build lua5.3 64bit tested in unity5, unity4.6.4(32bit), add macro LUA_5_3 in script,
modify last line of "resumefunc" in LuaState.cs from "return unpack(ret)" to "return table.unpack(ret)".
Then test main.unity, the editor will crash with error:
---------------mono.dll caused an Access Violation (0xc0000005)
---------------in module mono.dll at 0033:ed8d331a.

I test the code, and found that the crash caused by visiting a table after using coroutine, the short example to produce the issue:
local c = coroutine.create(function()
		Yield(WaitForSeconds(2))  --<--------------- works fine if this line is commented
	end)
coroutine.resume(c)  --<--------------- works fine if this line is commented
local x=UnityEngine.GameObject("OoOo")
print(x)     --<---------------- you will get a crash

Debug in mono, found:
internal static int print(IntPtr L)
{
	int n = LuaDLL.lua_gettop(L);  --<---------------------------- crashed after calling this
        ...

BTW, I build the slua.dll with vc2013, Is there anything wrong if i setup a project and build dll with vc2013 ?
Did not find the reason yet...

**Comment by yaukeywang** [comment]
Tested on mac, unity4.6.4, built as a universal bundle, and the same thing appeared.

**Comment by pangweiwei** [comment]
fixed
