### ISSUE TITLE
Subscribe to C# Events in Lua

### ISSUE THREAD

**Issue by napalm44** [pangweiwei/slua#49]
Thank you for your response to my other posts.

I was wondering if SLua supported subscribing to C# events? I can see why this might be difficult/impossible, but wanted to see if you had any solution?

Thanks

**Comment by pangweiwei** [comment]
Why you not use delegate directly?

**Comment by napalm44** [comment]
How exactly would I accomplish this? Using anonymous delegates? How do I access the += and -= operators to register/deregister my Lua listener? A simple example would be awesome.

Thanks

**Comment by yongkangchen** [comment]
@napalm44 don't you see examples in https://github.com/pangweiwei/slua/blob/master/Assets/Slua/Resources/delegate.txt?
