### ISSUE TITLE
Issues with variable args number

### ISSUE THREAD

**Issue by Playermet** [pangweiwei/slua#50]
1) Overloaded methods with different args number and `params` used comparison number of args, instead of `matchType` or something else.
Reproduce example:
`public void func6(string str, params object[] args) {}`
`public void func6(string str, int a, params object[] args) {}`

2) Overloaded methods with `params` argument handled with `matchType` as plain array. As result, caused 'No matched override function to call' error.
Reproduce example:
`public void func6(string str, params object[] args) {}`
`public void func6(int a, params object[] args) {}`

**Comment by pangweiwei** [comment]
Any function with params parameter can't support overload it.
