### ISSUE TITLE
C# Events and Delegates

### ISSUE THREAD

**Issue by napalm44** [pangweiwei/slua#51]
Thank you for your response to my other posts.

I was wondering if SLua supported subscribing to C# events? I can see why this might be difficult/impossible, but wanted to see if you had any solution?

I knwo you mentioned to use delegates directly, but I'm not sure if you mean your Lua delegates or C# delegates? If c# do you mean anonymous delegate? How do I access the += and -= operators to register/deregister my Lua listener? A simple example would be awesome.

Thanks!

**Comment by pangweiwei** [comment]
see delegate demo



sineysan@163.com
 
From: napalm44
Date: 2015-06-25 14:31
To: pangweiwei/slua
Subject: [slua] C# Events and Delegates (#51)
Thank you for your response to my other posts.
I was wondering if SLua supported subscribing to C# events? I can see why this might be difficult/impossible, but wanted to see if you had any solution?
I knwo you mentioned to use delegates directly, but I'm not sure if you mean your Lua delegates or C# delegates? If c# do you mean anonymous delegate? How do I access the += and -= operators to register/deregister my Lua listener? A simple example would be awesome.
Thanks!
