### ISSUE TITLE
slua应该避免unity crash

### ISSUE THREAD

**Issue by yongkangchen** [pangweiwei/slua#52]
很多情况下，预设修改后，点apply并不会立即保存到硬盘上，而是unity3d退出的时候才存盘。当unity3d crash的时候，预设修改就不会存盘而直接丢失。

所以建议slua应该避免unity crash.

**Comment by gizie** [comment]
可以在改完预设apply之后save project就可以保存到硬盘

**Comment by yongkangchen** [comment]
@gizie 嗯，有时候做预设的人难免会忘记

**Comment by pangweiwei** [comment]
你说的是什么crash？

**Comment by yongkangchen** [comment]
see #53
