### ISSUE TITLE
Nested Classes

### ISSUE THREAD

**Issue by napalm44** [pangweiwei/slua#54]
Hi,
We were experimenting with using Nested classes and noticed that Slua does not seem to be compatible. Specifically, when we use the [CustomLuaClass] attribute on a nested class, these classes are appended to their container class with a "+", which causes compilation to fail.

**Comment by pangweiwei** [comment]
Did you update your slua to lastest version?

**Comment by napalm44** [comment]
We are on .81. Is this fixed on a more recent version?

**Comment by pangweiwei** [comment]
Give me test code for your case.

**Comment by Playermet** [comment]
Can be fixed that way: replace LuaCodeGen.cs:1558
`Write(file, "{3}{2}.{0}({1});", m.Name, FuncCall(m), t.FullName, ret);`
with
`Write(file, "{3}{2}.{0}({1});", m.Name, FuncCall(m), t.FullName.Replace("+", "."), ret);`

**Comment by pangweiwei** [comment]
I had fixed in a good way.
