### ISSUE TITLE
[help]OSX built slua bundle doesn't work properly on Unity5.0

### ISSUE THREAD

**Issue by xophiix** [pangweiwei/slua#6]
![image](https://cloud.githubusercontent.com/assets/475227/6692121/bb7f1fec-cd05-11e4-999a-10c4900273d9.png)
course `LuaDLL.luaL_newstate()` return null. the prebuilt slua.bundle from git works right.

my slua.bundle xcode project compile slua.c and link with just built libluajit_x86.a and libluajit_x86_64.a to generate the universal bundle. is there any specific build settings need to apply?
![image](https://cloud.githubusercontent.com/assets/475227/6692228/5f05d1e2-cd06-11e4-8c73-9eef12be58e1.png)

I build the luajit using following script:
```
cd luajit
make clean
make CC="gcc -m32" BUILDMODE=static
cp src/libluajit.a ../osx/libluajit_x86.a

make clean
make CC="gcc" BUILDMODE=static
cp src/libluajit.a ../osx/libluajit_x86_64.a
```

another hint is I found my slua.bundle(nearly 1M) much bigger than prebuilt one from git(397k)

**Comment by pangweiwei** [comment]
luajit not support x64 arch on mac os x, so prebuild slua.bundle using lua5.15 for support max x64

**Comment by xophiix** [comment]
@pangweiwei  thanks.
btw I suggest slua source should include most platform build scripts or makeFile to simply the custom build process.
