### ISSUE TITLE
Lua errors list in C#

### ISSUE THREAD

**Issue by yongkangchen** [pangweiwei/slua#64]
These function call may lead unity crash:
- [ ] `public static extern int luaL_checkinteger(IntPtr luaState, int stackPos);`
- [ ] `public static extern double luaL_checknumber(IntPtr luaState, int stackPos);`
- [ ] `public static extern int luaS_rawnetobj(IntPtr luaState, int obj);`
- [ ] `public static extern void luaS_checkVector2(IntPtr l, int p, out float x, out float y);`
- [ ] `public static extern void luaS_checkVector3(IntPtr l, int p, out float x, out float y, out float z);`
- [ ] `public static extern void luaS_checkVector4(IntPtr l, int p, out float x, out float y, out float z, out float w);`
- [ ] `public static extern void luaS_checkQuaternion(IntPtr l, int p, out float x, out float y, out float z, out float w);`
- [ ] `public static extern void luaS_checkColor(IntPtr l, int p, out float x, out float y, out float z, out float w);`

**Comment by pangweiwei** [comment]
fixed
