### ISSUE TITLE
引用类型属性设置为null时候报参数错误bug.

### ISSUE THREAD

**Issue by tenvick** [pangweiwei/slua#66]
C#
class RTSCamera{
public LuaFunction  onMoveFinish;
}

lua
RTSCamera.onMoveFinish=nil 

会报参数类型不匹配错误

**Comment by yongkangchen** [comment]
确实不支持。推荐换个写法, 定义onMoveFinish类型为delegate或者Action

**Comment by yongkangchen** [comment]
所有的c#引用类型，原则上check的时候应该可以为nil的

**Comment by yongkangchen** [comment]
Fixed by f74ded48eb6394098fea00ccb902919ba4587ec6
