### ISSUE TITLE
参数为Vector3[]时候类型匹配不上

### ISSUE THREAD

**Issue by tenvick** [pangweiwei/slua#67]
EG：C#
class Helper{
//重载方法中有 数组
public static void move(GameObject obj,Vector3[] paths,float t){}
//有重载方法
public static void move(GameObject obj,Vector pos,float t){}
}
上面的函数会调用不了
lua
local paths={}
table.insert(paths,Vector3(0.1,1,0))
table.insert(paths,Vector3(1.1,1,2.3))
Helper. move(go,paths,1)

报错 No matched override function to call

**Comment by yongkangchen** [comment]
slua暂时对数组的支持不全，你需要自行添加`Vector3[]`的支持到luaobject_overload.cs(或者你新建一个cs文件)，实现方法参考`static public bool checkType(IntPtr l, int p, out string[] t)`如下：
```
		static public bool checkType(IntPtr l, int p, out Vector3[] t)
		{
			LuaDLL.luaL_checktype(l, p, LuaTypes.LUA_TTABLE);
			int n = LuaDLL.lua_rawlen(l, p);
			t = new Vector3[n];
			for (int k = 0; k < n; k++)
			{
				LuaDLL.lua_rawgeti(l, p, k + 1);
				checkType(l, -1, out t[k]);
				LuaDLL.lua_pop(l, 1);
			}
			return true;
		}
```

**Comment by pangweiwei** [comment]
你需要在LuaObject_overload.cs加入vector3[]的的checkType，

static public bool checkType(IntPtr l, int p, out Vector3[] array)
		{
			...
		}

**Comment by yongkangchen** [comment]
所以问题是c#里数组作为参数，lua调用时重载无法匹配
