### ISSUE TITLE
Error in checkType() when managed Vector3[] value is passed from luastate to managed function 

### ISSUE THREAD

**Issue by Salada** [pangweiwei/slua#69]
https://github.com/pangweiwei/slua/blob/master/Assets/Slua/Script/LuaObject_overload.cs#L56-L68

I attempt to pass Managed Vector3[] object as parameter from luastate to c sharp function.
but, an error is occurred. 

following example code.

* in C#
`
[SLua.StaticExport]	static public void Path(Transform target, Vector3[] path, float duration, string pathType, string ease, bool orientToPath = true) {
`

* luascript
`
Path(params.root.transform, GetPath(params), params.event:GetValue('m_movingTime'), 'CatmullRom', 'Linear', params.event:GetValue('m_orientToPath'))
`

return type of GetPath is Managed Vector3[] object.

* my workaround solution : https://gist.github.com/Salada/7c82fab23cf4d6e8cbf1

I wish you resolve this problem in your way, if you want.

thanks.

**Comment by yongkangchen** [comment]
I guess there is a missing function in LuaObject_overload.cs:
```
public static void pushValue(IntPtr l, Vector3[] r)
{
	if (r == null)
	{
		LuaDLL.lua_pushnil(l);
		return;
	}
	LuaDLL.lua_createtable(l, r.Length, 0);
	for (int n = 0; n < r.Length; n++)
	{
		pushValue(l, r[n]);
		LuaDLL.lua_rawseti(l, -2, n + 1);
	}
}
```
please add and try again

**Comment by Salada** [comment]
work done. thanks!


but without my issue, remain concern.

if array size is too many large, i think this operation is very heavy. 
why you decide to convert table? only for indexing issue? or implementation bring to increase slua system design complexity?

i wish to hear your opinion. thanks.

**Comment by yongkangchen** [comment]
I think array size in unity usages should not be too large. Auto convert table make us easy to use array in most usages.
When encounter any performance problem such as large array size in very few cases, I think developer can write flexible `LuaCSFunction` in c# like https://github.com/pangweiwei/slua/blob/master/Assets/Slua/example/Custom.cs#L33, or c language function like https://github.com/pangweiwei/slua/blob/master/build/slua.c

**Comment by pangweiwei** [comment]
You also export type of List<Vector3> to pass vector3 array between lua and c#, if so, c# passed userdata to lua avoid heavy create/copy content to lua.
