### ISSUE TITLE
LuaSvr cannot add custom native lib registration before call it's `main` function

### ISSUE THREAD

**Issue by xophiix** [pangweiwei/slua#7]
I compile a custom native lua lib `A` into slua plugin.
When I use LuaSvr("xxx"), it call the file's "main" function to start,  but inside the function there's code depends on the lib `A`. I need to register the A lib after luastate created and before the main function execution.  But there's no way to achieve this with LuaSvr right now. I think it could provide an option whether to call the main function in the LuaSrv contructor.

Also I could workaround by manually create LuaState and do the bind stuff LuaSrv does to insert my custom register code,  or leave 'main' function empty and call another real `main` later. But I don't think it's a good design.

Please take a consider about that.

**Comment by pangweiwei** [comment]
ok, updated.

Now, you can pass null for LuaSvr constructor and call start with main script name later.
