### ISSUE TITLE
Stack is left inflated by missing pop in LuaObject_basetype.cs checkType(IntPtr l, int p, out Type t)

### ISSUE THREAD

**Issue by jshmrsn** [pangweiwei/slua#70]
I was encountering an issue where the stack size (top) was increased after a binding called checkType. This confused a checkParams call later on because checkParams thought it had more inputs than it actually had (because top was increased).

Within the LuaTypes.LUA_TTABLE switch case, if the __type rawget pushes a nil value on to the stack, then the else case immediately does another rawget for __fullname without ever popping the nil value from __type off the stack. Now, both the values for __type and __fullname are on the stack, and the pop at the end of the else case only pops the __fullname value, but does not pop the nil value from __type.

I believe a fix is to add another pop at the beginning of the else case, right before pushing the __fullname string.

**Comment by pangweiwei** [comment]
Thanks for feedback, had fixed.
