### ISSUE TITLE
3rdDLL and custom export same Type lead to compile error

### ISSUE THREAD

**Issue by DebugClub** [pangweiwei/slua#72]
Assets/Slua/LuaObject/Dll/LuaDelegate_UIEventListener_VoidDelegate.cs(12,29): error CS0111: A member `SLua.LuaDelegation.checkDelegate(System.IntPtr, int, out UIEventListener.VoidDelegate)' is already defined. Rename this member or use different parameter types

**Comment by pangweiwei** [comment]
There is a temporary solution, change export directory to same directory, same type of delegate will be overwrite.
