### ISSUE TITLE
Error in Unity 5.2.1 when try to export to android/ios

### ISSUE THREAD

**Issue by heha** [pangweiwei/slua#74]
This error is different from last thread. It also occur on normal Unity 5.2.1f1 with no patch release. In Unity 5.2.1, it can play the example directly in Unity Editor but error when tried to export to mobile.

Assets/Slua/LuaObject/Unity/Lua_UnityEditor_Advertisements_AdvertisementSettings.cs(12,33): error CS0103: The name `UnityEditor' does not exist in the current context

Assets/Slua/LuaObject/Unity/Lua_UnityEditor_Advertisements_AdvertisementSettings.cs(146,52): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?

Assets/Slua/LuaObject/Unity/Lua_UnityEditor_Advertisements_AdvertisementSettings.cs(146,17): error CS1502: The best overloaded method match for `SLua.LuaObject.createTypeMetatable(System.IntPtr, LuaInterface.LuaCSFunction, System.Type)' has some invalid arguments

Assets/Slua/LuaObject/Unity/Lua_UnityEditor_Advertisements_AdvertisementSettings.cs(146,17): error CS1503: Argument `#3' cannot convert `object' expression to type `System.Type'

Error building Player because scripts had compiler errors

**Comment by pangweiwei** [comment]
You can add 
"Advertisements",
"UnityEditor",

to list of OnGetNoUseList function to skip them to export. Meanwhile I had fix it.
