### ISSUE TITLE
LuaState close does not actually close (as described by its own comments), plus another bug when re-enabling closing

### ISSUE THREAD

**Issue by jshmrsn** [pangweiwei/slua#75]
I've been intentionally closing my LuaState objects for awhile, believing that was closing the LuaVMs. I was very confused by why my Unity editor sometimes would fail to allocate new pointers in my native extensions. I eventually discovered the comments in LuaState:

```
				// be careful, if you close lua vm, make sure you don't use lua state again,
				// comment this line as default for avoid unexpected crash.
				// LuaDLL.lua_close(L);
				// L = IntPtr.Zero;
```

This was very surprising to me. While it's nice that the comments are there describing why you commented those lines out, there's nothing leading users of Slua to those comments. Either way, not closing the lua VM because of an "unexpected crash" is simply hiding other issue with the user's code if those crashes occur. Indeed, once I added the lua_close back, I did not start to experience other issues, but those issues were real and needed to be fixed.

In fact, one of the issues I discovered by re-adding lua_close was a rare (but very annoying) bug with Slua. In ObjectCache.del, the lua state is correctly removed from the multiState map, BUT oldl and oldoc are not cleared out (set to IntPtr.Zero / null). I believe this leads to a rare condition, where if a lua state is destroyed, and then another is created, the second lua state may have the exact same pointer address as the previous. Because it has the same address as before, the cache incorrectly pulls up the dead cache from oldoc.

Similarly, when a LuaState is closed, it should be removed from LuaState.statemap, and LuaState.oldptr and LuaState.oldstate should be cleared out. This doesn't appear to be happening on master, either.

**Comment by pangweiwei** [comment]
Not close lua vm used for user use Lua api again on lua been close, if so caused crash , there is nothing other bug. If you make sure don't use lua on closed , you can close it.

发自我的 iPhone

**Comment by pangweiwei** [comment]
Yes, some static variants are not cleared, let me think.

**Comment by pangweiwei** [comment]
I had fix.
