### ISSUE TITLE
why can't some UnityEngine's struct without explicit constructor construct in Lua

### ISSUE THREAD

**Issue by xophiix** [pangweiwei/slua#8]
like Physics.RaycastHit

I should've use `local a = Physics.RaycastHit()`, it's a struct, without explicit constructor though, it's allowed to construct obviously in C#.
but the binding code is like:
```
static public int constructor(IntPtr l) {
		LuaDLL.luaL_error(l,"New object failed.");
		return 0;
	}
```
It doesn't make sense

**Comment by pangweiwei** [comment]
ok, i will remove them.

**Comment by xophiix** [comment]
@pangweiwei what do u mean by remove them?
I mean I need to construct them in lua without "New object failed" error prompt

**Comment by pangweiwei** [comment]
what is it used for? 
you can use 2nd return value to get out modifier parameter, like:
local ok,hitinfo = Physics.Raycast(from,to)

Not necessary to construct RaycastHit.

**Comment by xophiix** [comment]
How could it possible?
```c#
Physics.Raycast(from,to)
Physics.Raycast(from,to, out hitInfo)
```
both overload form exists, how to distinguish which one to use
your code need 3 parameter to be passed in:
```c#
if(matchType(l,argc,1,typeof(UnityEngine.Vector3),typeof(UnityEngine.Vector3),typeof(UnityEngine.RaycastHit))){
	UnityEngine.Vector3 a1;
	checkType(l,1,out a1);
	UnityEngine.Vector3 a2;
	checkType(l,2,out a2);
	UnityEngine.RaycastHit a3;
	System.Boolean ret=UnityEngine.Physics.Raycast(a1,a2,out a3);
	pushValue(l,ret);
	pushValue(l,a3);
	return 2;
}
```

**Comment by xophiix** [comment]
btw  `RaycastHit` is just a specific case about struct type without declared constructor
there are plenty of this kind of struct there for different use case, including construct directly.
we can't say because `RaycastHit` need not construct  so all the others needn't.

**Comment by pangweiwei** [comment]
ok, fixed
