### ISSUE TITLE
Is there a way to handle exception from doString()?

### ISSUE THREAD

**Issue by heha** [pangweiwei/slua#80]
I coded something like this:

  Lua = new LuaSvr();
  Lua.init(null, LoadLuaComplete, false);
  try
        {
            Lua.luaState.doString("someUncaughtException()", "chunkName");
        }
        catch (Exception e)
        {
            Debug.Log(e.message);
        }

But it cannot caught an error in lua. What should I do?

**Comment by pangweiwei** [comment]
All codes that access lua state should move to LoadLuaComplete callback, can not call member of luaState following init.

**Comment by pangweiwei** [comment]
code like this will work fine:

Lua.init(null,()=>{
Lua.luaState.doString("someUncaughtException()", "chunkName");
}
,false);

**Comment by heha** [comment]
@pangweiwei 

Sorry for the wrong example. I think I should attached the whole project here:

http://levelup.in.th/TestLua.zip

It's not that the code is working before lua init is completed. Please extract the project and open the scene Main in your example. I modified Main.cs and main.txt to test this out. Now, foo function looked like this:

function foo(a,b,c)
	print(h.j)
	return a,b,c,"slua"
end

This will force an exception. Next, I edited errorReport() in LuaState.cs and comment out Debug.LogError(LuaDLL.lua_tostring(L, -1))

With this, there will be nothing left to report an error. I'm also not sure if I should hack the code to throw an exception instead of Debug.LogError or not because it may break the code.

If you asked me why I do not use Application.logMessageReceived to receive an error from Debug.LogError, it's because I want to handle the exception separate from other Debug.LogError in the application. For example, I want to show an error to user when lua do something wrong with different error message from other error. That's why I want try catch to be able to catch exception to work on my own error handling.

**Comment by pangweiwei** [comment]
I think you could modify doBuffer function like:

public bool doBuffer(byte[] bytes, string fn, out object ret)
		{
			ret = null;
            int errfunc = LuaObject.pushTry(L);
			if (LuaDLL.luaL_loadbuffer(L, bytes, bytes.Length, fn) == 0)
			{
				if (LuaDLL.lua_pcall(L, 0, LuaDLL.LUA_MULTRET, errfunc) != 0)
				{
                                        goto err;
				}
				LuaDLL.lua_remove(L, errfunc); // pop error function
				ret = topObjects(errfunc - 1);
				return true;
			}
err:
			string err = LuaDLL.lua_tostring(L, -1);
			LuaDLL.lua_pop(L, 2);
			throw new Exception(err);
		}

**Comment by heha** [comment]
It threw an Exception now but it's empty string in
string err = LuaDLL.lua_tostring(L, -1);

However, I can use it with old Debug.LogError in errorReport(). Thank you very much!
