### ISSUE TITLE
Mac与Win上生成自定义类代码 endline的问题

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#84]
我看LuaCodeGen里面，是用file.WriteLine()来写入.
这导致利用mac生成的Custom class和利用win生成的custom class由于换行符的不同而产生冲突。
这在跨平台svn协作的时候产生比较大的问题。
是否改成统一的endline比较好呢？
比如
file.WriteLine(fmt) == >file.Write(fmt); file.Write("\r\n");

**Comment by pangweiwei** [comment]
如果是git，有设置，自动转换CRLF。
如果是svn，参考这个：
http://stackoverflow.com/questions/15687/how-can-i-convert-all-line-endings-to-crlf-lf-or-cr-during-svn-operations

**Comment by wlgys8** [comment]
还是蛮麻烦的，svn每次有新增文件都要重新设置过 svn:eol-style 才行.
或者改svn 全局配置。
两种方式都觉得不太好。
要么给slua加个配置，可以自己选择生成文件的EOL 使用 native,CRLF,CR,LF?

**Comment by pangweiwei** [comment]
这样也可以
