### ISSUE TITLE
editor切出run状态的时候，OnDestroy里若调用lua代码会导致editor crash

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#89]
c#:

	Class A :MonoBehaviour{
		public Delegate delegate

		void OnDestroy(){
			delegate()
		}
	}

lua:

	local a = gameobject:GetComponent(A)
	a.delegate = {'+=',function(){
		
	}}

以上这种情况，Editor停止Run状态的时候会调用OnDestroy,然后有几率导致Editor Crash.

**Comment by pangweiwei** [comment]
我有一个LuaSvrProxy的gameobject，他有一个order execute是999，保证了luasvr是最后被析构的，不知道这个东西自己是不是有bug，unity不能保证luasvr最后被析构的话就会出现你说的问题。

**Comment by wlgys8** [comment]
我测试了一下 在编辑器里 这个OnDestroy顺序确实是随机的.
mac Unity 5.2.0
有没有办法调用lua前加个检查?

**Comment by pangweiwei** [comment]
我试图merge了，结果发现有问题，又revert了，主要是out类型的参数还要考虑赋值。

**Comment by pangweiwei** [comment]
我测试了一下，使用MonoManager的Executetion Order 配置其他所有monobehavirou的数值都小于SLua.LuaSvrGameObject的9999就是可以的。

**Comment by pangweiwei** [comment]
通过写程序应该可以便利所有monobehavirour设置其数值。

**Comment by wlgys8** [comment]
我这边测试OnDestroy还是随机的，不知道什么情况

执行顺序:


![c9d11d9b-ea3c-4fbc-b7a7-ebdd8a5437d6](https://cloud.githubusercontent.com/assets/3798187/11060190/9817e0fe-87d9-11e5-8776-dd52c302c1cc.png)

执行结果1：
![769283ee-bd15-4629-8d53-10f34874e171](https://cloud.githubusercontent.com/assets/3798187/11060334/65246982-87da-11e5-835a-5e05d1db8a2e.png)
执行结果2：

另一张，图片总是上传失败，不传了

**Comment by wlgys8** [comment]
你试一下动态添加脚本 ,而不是事先在编辑器里绑定好

**Comment by wlgys8** [comment]
我刚测试了下，如果脚本预先都在场景里绑定好了，则顺序是固定的。
否则如果是运行时通过AddComponent绑定上去的，则destroy顺序是随机的

**Comment by pangweiwei** [comment]
AddComponent绑定上去后，程序修改，添加进入这个列表不知道行不行？

**Comment by wlgys8** [comment]
脚本都已经加到执行列表里了

**Comment by wlgys8** [comment]
http://answers.unity3d.com/questions/1016015/order-of-destroy-objects-and-ondestroy-event.html

有看到类似的问题

**Comment by pangweiwei** [comment]
我现在把luasrvgameobject里 dispose luastate的代码注视掉了，等到进程结束自然释放

**Comment by yongkangchen** [comment]
OnApplicationQuit呢？
http://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html

**Comment by pangweiwei** [comment]
也不行，我测试了

**Comment by wlgys8** [comment]
去掉dispose  暂时应该只能这样了
