### ISSUE TITLE
LuaSvr.init线程池与Resources.LoadSync冲突问题

### ISSUE THREAD

**Issue by mr-kelly** [pangweiwei/slua#90]
Unity 4.6.4

如果在LuaSvr.init之前，使用了Resources.LoadAsync函数，会导致init里的线程池执行到一半没有继续，然后导致Editor卡住，内存不停的增加，最后崩溃。

```csharp
Resources.LoadAsync(uixxxxx)
```

后面再进行

```csharp
LuaSvr.init(null, ()=>{
     onFinishInit();
});
```

经排查，发现线程池执行的函数doBind执行到一定情况，然后就没执行到最后100%

可能两个情况：
* doBind中某函数大量alloc，导致Editor崩溃(从任务管理器中可知内存在不停递增)
* 线程池执行的doBind被停掉了

**Comment by pangweiwei** [comment]
我反复测试，没有发现你说问题，如果可以，你可以做一个最小可以重现的工程发给我。
