### ISSUE TITLE
关于第三方dll动态库链接的问题

### ISSUE THREAD

**Issue by wlgys8** [pangweiwei/slua#99]
比如我要编译一个 3rd.dll，它依赖的 libs = [lua51.lib]
其中lua51.lib是luajit项目编译出来的

因为slua在make的时候把lua51.dll改名为了slua.dll放到项目里，但这个改名似乎会导致3rd.dll找不到依赖。
试过几种方案：
1. 把slua.dll名字改为lua51.dll,并对应修改dllimport的名字,则可以正常工作。
2. 把lua51.lib重命名成slub.lib,再link出3rd.dll,依然无法工作。
3. 直接修改msvcbuild.bat里的LJLIBNAME = slua.lib,进行编译，则可正常工作。

不知道关于这个问题,@pangweiwei 你怎么看？

**Comment by yongkangchen** [comment]
https://github.com/pangweiwei/slua/blob/3rd_luasocket_example/build/SConstruct#L8
mac下gcc使用: -Wl,-undefined -Wl,dynamic_lookup
win下vs看有不有这个编译选项或者类似的

**Comment by wlgys8** [comment]
恩 主要是vs上的问题，我再查查看

**Comment by pangweiwei** [comment]
我是直接使用方案3的，之前测试过lpeg，对应的可能需要修改build script

**Comment by wlgys8** [comment]
为什么slua.c 要跟lua的源码一起编译 而不是以动态库的形式去引用呢?  有什么考虑吗

**Comment by pangweiwei** [comment]
没啥，简单，不想在单独写slua的每个平台的编译脚本了。
